apiVersion: apps/v1
kind: Deployment
metadata:
    name: ncsmc2-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ncsmc2
    template:
        metadata:
            labels:
                app: ncsmc2
        spec:
            containers:
                - name: ncsmc2
                  image: docker.prorickey.xyz/prorickey/ncsmc2:0.1.0
                  ports:
                      - containerPort: 3000
            imagePullSecrets:
                - name: registry-creds
---
apiVersion: v1
kind: Service
metadata:
    name: ncsmc2-service
spec:
    selector:
        app: ncsmc2
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: NodePort
