apiVersion: apps/v1
kind: Deployment
metadata:
    name: ncsmc2-deployment
spec:
    revisionHistoryLimit: 3
    replicas: 1
    selector:
        matchLabels:
            app: ncsmc2
    template:
        metadata:
            labels:
                app: ncsmc2
        spec:
            containers:
                - name: ncsmc2
                  image: docker.prorickey.xyz/prorickey/ncsmc2:1.3.8
                  ports:
                      - containerPort: 3000
                  volumeMounts:
                      - name: localtime
                        mountPath: /etc/localtime
                        readOnly: true
                      - name: timezone
                        mountPath: /etc/timezone
                        readOnly: true
            imagePullSecrets:
                - name: registry-creds
            volumes:
                - name: localtime
                  hostPath:
                      path: /etc/localtime
                      type: File
                - name: timezone
                  hostPath:
                      path: /etc/timezone
                      type: File
---
apiVersion: v1
kind: Service
metadata:
    name: ncsmc2-service
spec:
    selector:
        app: ncsmc2
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: NodePort
